debug:
    enabled: false
telegram:
    token: <token>
storage:
    type: file
    options:
        placeholder: "placeholder"
http:
    addr: :80
admin:
    enabled: false
    usernames:
        - user1
        - user2
