name: Build on Pull Request to Master

on:
  pull_request:
    branches: 
      - master

jobs:
  antenna:
    name: Build Antenna
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      run: docker build -t antenna .
