name: Release Master

on:
  push:
    branches:
      - master

jobs:
  antenna:
    name: Release Antenna
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      run: docker build -t antenna .
    - name: Login Docker Registry
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
    - name: Tag Date
      run: docker tag antenna ${{ secrets.DOCKER_USER }}/antenna:$(date +%Y%m%d)
    - name: Push Date
      run: docker push ${{ secrets.DOCKER_USER }}/antenna:$(date +%Y%m%d)
    - name: Tag Latest
      run: docker tag antenna ${{ secrets.DOCKER_USER }}/antenna:latest
    - name: Push Latest
      run: docker push ${{ secrets.DOCKER_USER }}/antenna:latest
